import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import { readMessagesAndSendMessage } from './contacts';

// @ts-ignore
yargs(hideBin(process.argv))
  .command('readFileAndSendMessage', 'send SMS to contact or group of contacts', (yargs) => yargs
    .positional('url', {
      describe: 'smartthing-phevctl sms host',
      default: 'http://localhost:8098',
    }).positional('applicationId', {
      describe: 'SMS ApplicationId',
      type: 'string',
    }).positional('applicationSecret', {
      describe: 'SMS applicationServer ',
      type: 'string',
    }).positional('messagesFile', {
      describe: 'message json file generated by "e3372h_320 messages --exportFormat=json" ',
      type: 'string',
    }), async (argv) => {
    if (!argv.applicationId) {
      throw new Error('applicationId is not defined');
    }
    if (!argv.applicationSecret) {
      throw new Error('applicationSecret is not defined');
    }
    if (!argv.messagesFile) {
      throw new Error('applicationSecret is not defined');
    }
    await readMessagesAndSendMessage(argv.url,
      argv.applicationId,
      argv.applicationSecret,
      argv.messagesFile);
  })
  .parse();
