const Labels = {
  servicePort: 'Service Port',
  uiPort: 'UI Port',
  smartthingsAppId: 'Smartthings Application Id',
  smartthingsAppSecret: 'Smartthings Application Secret',
  save: 'Save',
  settings: 'Settings',
  devices: 'Devices',
  addDevice: 'Add Device',
  users: 'Users',
  addUser: 'Add User',
  actionId: 'Action',
  deviceLabel: 'Device Label',
  cooling10Mins: 'Cooling Mode 10 Mins',
  cooling20Mins: 'Cooling Mode 20 Mins',
  cooling30Mins: 'Cooling Mode 30 Mins',
  windscreen10Mins: 'Windscreen Mode 10 Mins',
  windscreen20Mins: 'Windscreen Mode 20 Mins',
  windscreen30Mins: 'Windscreen Mode 30 Mins',
  heating10Mins: 'Heating Mode 10 Mins',
  heating20Mins: 'Heating Mode 20 Mins',
  heating30Mins: 'Heating Mode 30 Mins',
  airconOn: 'Air conditioner On',
  airconOff: 'Air conditioner Off',
  headlightsOn: 'Headlights On',
  headlightsOff: 'Headlights Off',
  parkinglightsOn: 'Parkinglights On',
  parkinglightsOff: 'Parkinglights Off',
  username: 'Username',
  password: 'Password',
  delete: 'Delete',
  shard: 'Smartthings Portal Shard',
  macAddress: 'Outlander PHEV Client Mac Address',
  keycloakJson: 'Securing Applications using keycloak.json',
  testDevice: 'Test Action',
  actionTimeout: 'Action Timeout',
  language: 'Language',
};

export function getLabels() {
  return Labels;
}
