export const RussianLabels = {
  servicePort: 'Service Port',
  uiPort: 'UI Port',
  smartthingsAppId: 'Smartthings Application Id',
  smartthingsAppSecret: 'Smartthings Application Secret',
  save: 'Сохранить',
  settings: 'Настройки',
  devices: 'Устройства',
  addDevice: 'Добавить Устройство',
  users: 'Пользователи',
  addUser: 'Добавить Пользователя',
  actionId: 'Действие',
  deviceLabel: 'Название устройства',
  cooling10Mins: 'Режим Охлаждения на 10 Мин.',
  cooling20Mins: 'Режим Охлаждения на 20 Мин.',
  cooling30Mins: 'Режим Охлаждения на 30 Мин.',
  windscreen10Mins: 'Обогрев лобового окна на 10 мин.',
  windscreen20Mins: 'Обогрев лобового окна на 20 мин.',
  windscreen30Mins: 'Обогрев лобового окна на 30 мин.',
  heating10Mins: 'Режим Отопителя на 10 мин.',
  heating20Mins: 'Режим Отопителя на 20 мин.',
  heating30Mins: 'Режим Отопителя на 30 мин.',
  airconOn: 'Включить Климат контроль',
  airconOff: 'Отключить Климат Контроль',
  headlightsOn: 'Включить Фары',
  headlightsOff: 'Выключить Фары',
  parkinglightsOn: 'Включить Парковочные огни',
  parkinglightsOff: 'Выключить Парковочные огни',
  username: 'Имя пользователя',
  password: 'Пароль',
  delete: 'Удалить',
  shard: 'Smartthings Portal Shard',
  macAddress: 'MAC адрес',
  keycloakJson: 'Securing Applications using keycloak.json',
  testDevice: 'Протестировать устройство',
  actionTimeout: 'Максимальное время выполнения ',
  language: 'Язык',
  modalHelp: 'Где взять параметр ',
  modalStep1: '1. Откройте портал ',
  modalStep2: '2. Выбрать smartapps в вашей локации ',
  modalStep3: '3. Выберите созданное вами "remote-ctrl-gsm" ',
  modalStep4: '4. Возмите со страницы параметр ',
  modelYear: 'Год Выпуска PHEV',
  any: 'Любой',
  phev2019: '2019',
  battery: 'Заряд Батареи',
  updateValue: 'Обновить Текущее Значение',
  loading: 'Подождите идет загрузка...',
  batteryFactory: 'Множитель батареи',
};
