name: docker-armv6

on:
  push:
    branches: main

jobs:
  armv6:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./armv6
          file: ./armv6/Dockerfile
          platforms: linux/arm/v6
          push: true
          tags: |
            vassio/smartthings-phevctl:1.3.5-armv6
            vassio/smartthings-phevctl:latest-armv6
